### ISSUE TITLE
Plugins for new types

### ISSUE THREAD

**Issue by mohawk2** [graphql-perl/graphql-perl#13]
Currently, there is no easy way to add to the set of builtin types, especially `Scalar`. As inspired by a question from @zastavnitskiy, there needs to be a way to implement a new type, e.g. `GraphQL::Plugin::Type::CustomScalar`. On loading that, it would register itself with `GraphQL::Schema` (which currently has a hard-coded list of "builtins" to type objects) so that a schema which uses that type would "just work" with `from_doc`, etc.

Once implemented, I would then be able to move `DateTime` over to being a supplied example of that, since it is a Perl-only extension not available in the JS implementation.

**Comment by zastavnitskiy** [comment]
Hey, thank you for opening this!

Please, correct me if I'm wrong, but as I understand there is no big difference in having custom scalar types of having any other custom type — the fact that `ID`, `String`, `Int` are implemented inside of Scalar type is just an implementation detail of graphql-perl? Or there is another way to add non-scalar custom types?

Just for the reference, in case of Apollo, this is implemented by passing a [resolver map](https://www.apollographql.com/docs/graphql-tools/resolvers.html#Resolver-map) to `makeExecutableSchema` — I believe that similar implementation may work for perl version too.

Thank again for following up on it!

**Comment by mohawk2** [comment]
Hi Pavel,

Thanks for your interest!

You say "inside of Scalar type". I hope you agree that's because those types only make any sense as scalars. My concept of adding types via plugin would definitely allow including non-scalar types. The major reason to not worry about that is that it is already 100% idiomatic to define object, input, and interface types using the SDL (schema definition language). Indeed, that's more or less the point of SDL. The only sticking-point is the scalars, so that's the only type I can see anyone would add using this plugin scheme.

Do you see what I mean? If not, please say how and I will try to close any conceptual gaps :-)

**Comment by mohawk2** [comment]
By the way, the Apollo thing you cite I just see as a nicely concise JS way of doing the "programmatic" thing I mentioned above, which you can absolutely already do with the current code. That's just defining a Query object type, which you can already do, etc.

**Comment by mohawk2** [comment]
@zastavnitskiy I have now implemented this feature and released it as 0.33. You can make a plugin for any type you like, scalar or otherwise! Therefore, closing this. If you find any problems, please let me know!
