### ISSUE TITLE
cpanm install fails - unknown command pod2markdown

### ISSUE THREAD

**Issue by Sam-Kearns** [graphql-perl/graphql-perl#15]
I tried to install GraphQL::Schema module (via the Mojo plugin) on my system (CentOS 7 & Perl 5.24 via Perlbrew) but the installation fails due to GraphQL::Schema install requiring the command `pod2markdown` which is not installed by default.

```
pod2markdown lib/GraphQL.pm >README.md
/bin/sh: pod2markdown: command not found
make: *** [README.md] Error 127
-> FAIL Installing GraphQL failed. See /opt/ybi-services/.cpanm/work/1556511257.126/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'GraphQL' is not installed
-> FAIL Bailing out the installation for Mojolicious-Plugin-GraphQL-0.13.
```

If I do `cpanm Pod::Markdown` first, then GraphQL installs correctly.

The installation should install Pod::Markdown as a pre-requisite, or use something that is commonly available.

Thanks for writing GraphQL for Perl! :D

**Comment by mohawk2** [comment]
You're very welcome! I think this might have been due to a slight change in how I make the release affecting timestamps. Can you try again with 0.35, just released? I'll close this, but if I'm wrong and it fails, could you reopen?
