### ISSUE TITLE
Support directives for type language

### ISSUE THREAD

**Issue by yigarashi-9** [graphql-perl/graphql-perl#24]
The [specification](https://graphql.github.io/graphql-spec/June2018/) says type language supports directives for fields of ObjectTypeDefinition, InterfaceTypeDefinition, and InputTypeObjectDefinition. 

For example, a following definition should be supported.
(grpahql-perl does not support it now...)

```
type Query {
  field1: String @directive1
  field2: Int @directive2(arg: true)
}
```

This feature is useful to implement a tool like [graphql-cost-analysis](https://github.com/pa-bru/graphql-cost-analysis).

I have already implemented it and sent pull-request (see #23). Would you check the pull-request? I need your help to regain coverage, because I don't understand coveralls' mysterious behavior.

**Comment by mohawk2** [comment]
I don't understand it either! I'm not going to lose sleep over it at this time though. Thanks for your excellent PR, which is now merged.
