### ISSUE TITLE
Opt-out of Builtin `DateTime`

### ISSUE THREAD

**Issue by mangano-ito** [graphql-perl/graphql-perl#38]
We have our own `DateTime` type in the schema.
This conflicts the library-builtin `DateTime` custom scalar type,
so we would rather have an option not to include it.

`GraphQL::Schema` implicitly includes `GraphQL::Plugin::Type::DateTime` along.
Could we just drop `use` of it from the code?
It can be backward-compatibility-breaking change for those who expect it auto-included.

If you think that is a problem,
how about giving a method to unregister it instead?
`GraphQL::Plugin::Type` has a method `register`, but `unregister`.
Once we have a method to unregister a type, we can opt out `DateTime` safely.
This idea will keep the current behavior.

I would like to hear whether some of these proposal seem okay.
I'm ready to PR for that.

Thank you,

**Comment by mohawk2** [comment]
I'm quite open to changing the behaviour either to explicitly deregister the `DateTime` type, or even to not have it included by default (but opt-in-able) anymore. Since it's not part of the default GraphQL standard, that seems a reasonable thing to do.

What specific ideas did you have in mind?

**Comment by mangano-ito** [comment]
Good. I'm happy to hear that.

I'm going to remove `use GraphQL::Plugin::Type::DateTime` in `GraphQL::Schema` in my next PR #39.
Users would find it no longer enabled by default.
It's, though, still opt-in-able just by explicitly using it on their own so I guess it's okay.
